### ISSUE TITLE
Will this project stay unfinished?

### ISSUE THREAD

**Issue by ErikVogelLUH** [James-ZYM/APT-Pipe#1]
Hi,
I am a Computer Science student and want to use APT-Pipe for a student research project. Is this the entire code? It seems unfinished in step 3. If the code is unavailable, I would continue writing APT-Pipe for my project.
Best, Erik

**Comment by James-ZYM** [comment]
Hi Erik,
Thanks for reminding us and we have updated the git. Please check the entire code in latest version of main.py.
Best, James.

**Comment by James-ZYM** [comment]
Hi Erik,

We have updated the git. Please check the latest version. : )

Best,
James

在 2024年6月6日，00:15，ErikVogelLUH ***@***.***> 写道：

﻿

Hi,
I am a Computer Science student and want to use APT-Pipe for a student research project. Is this the entire code? It seems unfinished in step 3. If the code is unavailable, I would continue writing APT-Pipe for my project.
Best, Erik
